/* This file is autogenerated from the database. */
/* See src/desc/gen_proto */
/* Do not edit*/
entree functions_gp[]={
{"breakpoint",0,(void*)pari_breakpoint,1,"v","breakpoint(): interrupt the program and enter the breakloop. The program continues when the breakloop is exited."},
{"dbg_down",0,(void*)dbg_down,1,"vD1,L,","dbg_down({n=1}): (break loop) go down n frames. Cancel a previous dbg_up."},
{"dbg_err",0,(void*)dbg_err,1,"","dbg_err(): (break loop) return the error data of the current error, if any."},
{"dbg_up",0,(void*)dbg_up,1,"vD1,L,","dbg_up({n=1}): (break loop) go up n frames. Allow to inspect data of the parent function."},
{"quit",0,(void*)gp_quit,1,"vD0,L,","quit({status = 0}): quit, return to the system with exit status 'status'."},
{"whatnow",0,(void*)whatnow0,1,"vr","whatnow(key): if key was present in GP version 1.39.15, gives the new function name."},
{NULL,0,NULL,0,NULL,NULL} /* sentinel */
};
