#ifdef LONG_IS_64BIT
#define __AGM_ATAN_LIMIT                 60
#define __DIVRR_GMP_LIMIT                4
#define __EXPNEWTON_LIMIT                66
#define __F2x_MUL_KARATSUBA_LIMIT        15
#define __F2xqX_BARRETT_LIMIT            48
#define __F2xqX_DIVREM_BARRETT_LIMIT     292
#define __F2xqX_INVBARRETT_LIMIT         46
#define __F2xqX_REM_BARRETT_LIMIT        292
#define __Flx_BARRETT_HALFMULII_LIMIT    21
#define __Flx_BARRETT_KARATSUBA_LIMIT    1172
#define __Flx_BARRETT_MULII2_LIMIT       16
#define __Flx_BARRETT_MULII_LIMIT        448
#define __Flx_BARRETT_QUARTMULII_LIMIT   23
#define __Flx_DIVREM_BARRETT_LIMIT       768
#define __Flx_EXTGCD_LIMIT               241
#define __Flx_GCD_LIMIT                  1017
#define __Flx_HALFGCD_HALFMULII_LIMIT    48
#define __Flx_HALFGCD_KARATSUBA_LIMIT    77
#define __Flx_HALFGCD_MULII2_LIMIT       25
#define __Flx_HALFGCD_MULII_LIMIT        71
#define __Flx_HALFGCD_QUARTMULII_LIMIT   52
#define __Flx_INVBARRETT_HALFMULII_LIMIT 231
#define __Flx_INVBARRETT_KARATSUBA_LIMIT 5067
#define __Flx_INVBARRETT_MULII2_LIMIT    26
#define __Flx_INVBARRETT_MULII_LIMIT     1154
#define __Flx_INVBARRETT_QUARTMULII_LIMIT 139
#define __Flx_MUL_HALFMULII_LIMIT        5
#define __Flx_MUL_KARATSUBA_LIMIT        142
#define __Flx_MUL_MULII2_LIMIT           5
#define __Flx_MUL_MULII_LIMIT            7
#define __Flx_MUL_QUARTMULII_LIMIT       5
#define __Flx_REM_BARRETT_LIMIT          1266
#define __Flx_SQR_HALFSQRI_LIMIT         3
#define __Flx_SQR_KARATSUBA_LIMIT        316
#define __Flx_SQR_QUARTSQRI_LIMIT        3
#define __Flx_SQR_SQRI2_LIMIT            7
#define __Flx_SQR_SQRI_LIMIT             5
#define __FlxqX_BARRETT_LIMIT            17
#define __FlxqX_DIVREM_BARRETT_LIMIT     46
#define __FlxqX_EXTGCD_LIMIT             44
#define __FlxqX_GCD_LIMIT                470
#define __FlxqX_HALFGCD_LIMIT            60
#define __FlxqX_INVBARRETT_LIMIT         22
#define __FlxqX_REM_BARRETT_LIMIT        48
#define __FpXQX_BARRETT_LIMIT            12
#define __FpXQX_DIVREM_BARRETT_LIMIT     30
#define __FpXQX_EXTGCD_LIMIT             28
#define __FpXQX_GCD_LIMIT                191
#define __FpXQX_HALFGCD_LIMIT            35
#define __FpXQX_INVBARRETT_LIMIT         40
#define __FpXQX_REM_BARRETT_LIMIT        30
#define __FpX_BARRETT_LIMIT              38
#define __FpX_DIVREM_BARRETT_LIMIT       113
#define __FpX_EXTGCD_LIMIT               87
#define __FpX_GCD_LIMIT                  406
#define __FpX_HALFGCD_LIMIT              58
#define __FpX_INVBARRETT_LIMIT           111
#define __FpX_REM_BARRETT_LIMIT          111
#define __Fp_POW_BARRETT_LIMIT           127
#define __Fp_POW_REDC_LIMIT              17
#define __INVMOD_GMP_LIMIT               3
#define __INVNEWTON_LIMIT                75
#define __LOGAGMCX_LIMIT                 22
#define __LOGAGM_LIMIT                   6
#define __MULII_FFT_LIMIT                -1
#define __MULII_KARATSUBA_LIMIT          -1
#define __MULRR_MULII_LIMIT              55
#define __RgX_MUL_LIMIT                  9
#define __RgX_SQR_LIMIT                  38
#define __SQRI_FFT_LIMIT                 -1
#define __SQRI_KARATSUBA_LIMIT           -1
#define __SQRR_SQRI_LIMIT                12
#else
#define __AGM_ATAN_LIMIT                 89
#define __DIVRR_GMP_LIMIT                4
#define __EXPNEWTON_LIMIT                197
#define __F2x_MUL_KARATSUBA_LIMIT        23
#define __F2xqX_BARRETT_LIMIT            17
#define __F2xqX_DIVREM_BARRETT_LIMIT     46
#define __F2xqX_INVBARRETT_LIMIT         22
#define __F2xqX_REM_BARRETT_LIMIT        48
#define __Flx_BARRETT_HALFMULII_LIMIT    23
#define __Flx_BARRETT_KARATSUBA_LIMIT    905
#define __Flx_BARRETT_MULII2_LIMIT       647
#define __Flx_BARRETT_MULII_LIMIT        433
#define __Flx_BARRETT_QUARTMULII_LIMIT   20
#define __Flx_DIVREM_BARRETT_LIMIT       1289
#define __Flx_EXTGCD_LIMIT               632
#define __Flx_GCD_LIMIT                  2514
#define __Flx_HALFGCD_HALFMULII_LIMIT    78
#define __Flx_HALFGCD_KARATSUBA_LIMIT    139
#define __Flx_HALFGCD_MULII2_LIMIT       537
#define __Flx_HALFGCD_MULII_LIMIT        91
#define __Flx_HALFGCD_QUARTMULII_LIMIT   37
#define __Flx_INVBARRETT_HALFMULII_LIMIT 240
#define __Flx_INVBARRETT_KARATSUBA_LIMIT 3600
#define __Flx_INVBARRETT_MULII2_LIMIT    1815
#define __Flx_INVBARRETT_MULII_LIMIT     1293
#define __Flx_INVBARRETT_QUARTMULII_LIMIT 73
#define __Flx_MUL_HALFMULII_LIMIT        7
#define __Flx_MUL_KARATSUBA_LIMIT        90
#define __Flx_MUL_MULII2_LIMIT           152
#define __Flx_MUL_MULII_LIMIT            8
#define __Flx_MUL_QUARTMULII_LIMIT       7
#define __Flx_REM_BARRETT_LIMIT          689
#define __Flx_SQR_HALFSQRI_LIMIT         4
#define __Flx_SQR_KARATSUBA_LIMIT        159
#define __Flx_SQR_QUARTSQRI_LIMIT        4
#define __Flx_SQR_SQRI2_LIMIT            470
#define __Flx_SQR_SQRI_LIMIT             5
#define __FlxqX_BARRETT_LIMIT            17
#define __FlxqX_DIVREM_BARRETT_LIMIT     46
#define __FlxqX_EXTGCD_LIMIT             44
#define __FlxqX_GCD_LIMIT                1289
#define __FlxqX_HALFGCD_LIMIT            89
#define __FlxqX_INVBARRETT_LIMIT         22
#define __FlxqX_REM_BARRETT_LIMIT        48
#define __FpXQX_BARRETT_LIMIT            12
#define __FpXQX_DIVREM_BARRETT_LIMIT     30
#define __FpXQX_EXTGCD_LIMIT             28
#define __FpXQX_GCD_LIMIT                182
#define __FpXQX_HALFGCD_LIMIT            35
#define __FpXQX_INVBARRETT_LIMIT         40
#define __FpXQX_REM_BARRETT_LIMIT        30
#define __FpX_BARRETT_LIMIT              44
#define __FpX_DIVREM_BARRETT_LIMIT       116
#define __FpX_EXTGCD_LIMIT               81
#define __FpX_GCD_LIMIT                  414
#define __FpX_HALFGCD_LIMIT              55
#define __FpX_INVBARRETT_LIMIT           121
#define __FpX_REM_BARRETT_LIMIT          127
#define __Fp_POW_BARRETT_LIMIT           11
#define __Fp_POW_REDC_LIMIT              3
#define __INVMOD_GMP_LIMIT               3
#define __INVNEWTON_LIMIT                93
#define __LOGAGMCX_LIMIT                 32
#define __LOGAGM_LIMIT                   45
#define __MULII_FFT_LIMIT                -1
#define __MULII_KARATSUBA_LIMIT          -1
#define __MULRR_MULII_LIMIT              19
#define __RgX_MUL_LIMIT                  7
#define __RgX_SQR_LIMIT                  34
#define __SQRI_FFT_LIMIT                 -1
#define __SQRI_KARATSUBA_LIMIT           -1
#define __SQRR_SQRI_LIMIT                9
#endif
